export const DEFAULT_CONFIG = {
  underline: {},
  highlight: {},
  codeBlock: {},
  figCaption: {},
  embeds: {},
  link: {},
  emojiSuggestion: {},
  emojiPicker: {},
  customCommands: {},
  characterCount: {},
  focus: { mode: "shallowest" },
  starterKit: { document: false, codeBlock: false, code: false },
  placeholder: {},
};
