export const DEFAULT_CONFIG = {
  underline: {},
  highlight: {},
  codeBlock: {},
  figCaption: {},
  embeds: {},
  link: {},
  emojiSuggestion: {},
  emojiPicker: {},
  customCommands: {},
  characterCount: {},
  focus: {},
  starterKit: {},
  placeholder: {},
};
