version: v1.0
fail_fast: true
is_cypress: false
plan: standard-2

triggers:
  - event: branch
    branch_name: main

commands:
  - checkout
  - neetoci-version node 22.13
  - bash ./.scripts/bump_version.sh
