version: v1.0
plan: standard-2
name: neetoCi
global_job_config:
  setup:
    - checkout
    - neetoci-version node 18.12.0
    - cache restore
    - yarn install
    - cache store
  jobs:
    - name: CiChecks
      commands:
        - npx neeto-audit-frontend

triggers:
  - event: branch
    branch_name: main
  - event: pull_request
