module.exports = {
  rules: {
    "@bigbinary/neeto/api-connector-name-should-match-filename": "error",
    "@bigbinary/neeto/api-connector-should-use-default-export": "error",
    "@bigbinary/neeto/combine-multiple-independent-awaits": "warn",
    "@bigbinary/neeto/consistent-button-link-anchor": "warn",
    "@bigbinary/neeto/no-blacklisted-imports": "warn",
    // "@bigbinary/neeto/no-dangling-constants": "error",
    "@bigbinary/neeto/no-excess-function-arguments": "warn",
    "@bigbinary/neeto/no-globalProps-destructure": "error",
    "@bigbinary/neeto/no-globalProps-reassignment": "error",
    "@bigbinary/neeto/no-namespace-specifier-import-for-ramda": "error",
    "@bigbinary/neeto/no-redundant-jsx-expression": "error",
    "@bigbinary/neeto/no-redundant-string-templates": "error",
    "@bigbinary/neeto/no-missing-localization": "error",
    // "@bigbinary/neeto/no-routes-destructure-and-reassignment": "error",
    "@bigbinary/neeto/ramda-tips": "warn",
    // "@bigbinary/neeto/routes-should-be-declared-and-default-exported": "error",
    // "@bigbinary/neeto/routes-should-match-object-path": "error",
    "@bigbinary/neeto/use-axios-config-for-passing-query-parameters": "warn",
    // "@bigbinary/neeto/use-common-routes": "error",
    "@bigbinary/neeto/use-snake-case-for-api-connector-filename": "error",
  },
};
