import { EDITOR_OPTIONS } from "constants/common";

export const DEFAULT_EDITOR_OPTIONS = [
  EDITOR_OPTIONS.BOLD,
  EDITOR_OPTIONS.ITALIC,
  EDITOR_OPTIONS.UNDERLINE,
  EDITOR_OPTIONS.STRIKETHROUGH,
  EDITOR_OPTIONS.LINK,
  EDITOR_OPTIONS.PARAGRAPH,
  EDITOR_OPTIONS.H1,
  EDITOR_OPTIONS.H2,
  EDITOR_OPTIONS.LIST_BULLETS,
  EDITOR_OPTIONS.LIST_ORDERED,
  EDITOR_OPTIONS.BLOCKQUOTE,
  EDITOR_OPTIONS.CODE_BLOCK,
];
