import { ADD_ON_OPTIONS } from "constants/common";

export const DEFAULT_ADD_ON_OPTIONS = [
  ADD_ON_OPTIONS.FONT_COLOR,
  ADD_ON_OPTIONS.FONT_SIZE,
  ADD_ON_OPTIONS.BOLD,
  ADD_ON_OPTIONS.ITALIC,
  ADD_ON_OPTIONS.UNDERLINE,
  ADD_ON_OPTIONS.STRIKETHROUGH,
  ADD_ON_OPTIONS.LINK,
  ADD_ON_OPTIONS.LIST_BULLETS,
  ADD_ON_OPTIONS.LIST_ORDERED,
];
