/** Icons generated by create-react-icons. Don't edit this file directly. **/
import React from "react";
import PropTypes from "prop-types";

export function Undo(props) {
  const { size, color, ...other } = props;
  return (
    <svg viewBox="0 0 24 24" fill="none" height={size} width={size} {...other}>
      <path
        d="M5.68433 12.6842V12.6842C5.68433 16.1723 8.512 19 12.0001 19C15.4882 19 18.3159 16.1723 18.3159 12.6842C18.3159 9.19608 15.4882 6.36841 12.0001 6.36841H6.4738"
        stroke={color}
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path
        d="M8.8423 4L6.47388 6.36842"
        stroke={color}
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
      <path
        d="M8.8423 8.73683L6.47388 6.36841"
        stroke={color}
        strokeWidth="1.5"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </svg>
  );
}

Undo.defaultProps = {
  color: "currentColor",
  size: 24,
};

Undo.propTypes = {
  color: PropTypes.string,
  size: PropTypes.oneOfType([PropTypes.string, PropTypes.number]),
};
