name: Publish to npm

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup NodeJS LTS version
        uses: actions/setup-node@v3
        with:
          node-version: "22.13"

      - name: Setup the project
        run: yarn install

      - name: Generate production build
        run: yarn bundle

      - name: Publish the package on NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          access: "public"
          token: ${{ secrets.NPM_TOKEN }}
          tag: ${{ github.event.release.prerelease && 'beta' || 'latest' }}

      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          input-token: ${{ secrets.INPUT_TOKEN }}

      - name: Upload public assets to CDN
        if: ${{ !github.event.release.prerelease }}
        run: yarn upload
